config/routes.rb
Rails.application.routes.draw do

  
  mount Flipflop::Engine => "/flipflop"

  
  devise_for :users, controllers: { registrations: "users/registrations"}

  devise_scope :user do 
    get "/users/:id/edit_admin" => "users/registrations#edit_admin"
    get "/user/create_user" => "users/registrations#create_user"
    post "/user/create_user" => "users/registrations#create_user_master"
    patch "/users/edit_admin" => "users/registrations#update_admin"
    put "/users/edit_admin" => "users/registrations#update_admin"
    delete "/user/admin" => "users/registrations#delete_user"

  end 

  # scope '/api' do
  #   resources :groups, except: [:new, :edit]
  #   resources :articles
  # end

  mount Flipper::UI.app(Flipper) => '/flipper'




  get 'subscriptions/index'
  get 'welcome/index'

  resources :articles

  resources :authors

  resources :products

  resources :categories

  resources :subscribers

  resources :magazines

  resources :movies do
    resources :comments, module: :movies
  end

  resources :actors do
    resources :comments, module: :actors
  end

  namespace :api do
    namespace :v1 do
      #post 'articles', to: 'articles#showcols'
      resources :articles do
        resources :author
      end

      resources :authors do
        resources :article
      end
    end
  end

  get '/categorization', to: 'categorization#index'

  get '/categorization/:id', to: 'categorization#show'

  get '/subscriptions', to: 'subscriptions#index'

  get '/users', to: 'users#index'

  get '/users/:id', to: 'users#show', as: 'users_show'

  get '/users/:id/edit_admin', to: 'users/registrations#edit_admin', as: 'edit_user'

  get '/user/create_user', to: 'users/registrations#create_user', as: 'create_user'

  delete '/user/admin', to: 'users/registrations#delete_user', as: 'delete_user'

  post '/user/demo/sql_injection', to: 'users#demo_sql_injection', as: 'demo_sql_injection'



  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'api/status', controller: 'application', action: 'status'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/article.rb
class Article < ApplicationRecord
	validates_presence_of :title, message: 'must exist'
	validates_presence_of :body, message: 'must exist'
	# belongs_to :author
	belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
	before_destroy do
    products.each { |product| product.destroy }
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :categories
end

app/models/school.rb
class School < ApplicationRecord
	belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
	has_one :school
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  has_many :subscriptions
  has_many :magazines, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :subscriber
	belongs_to :magazine
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 8..128

  # validates :password, :format => {:with => /((?=.*\d).{1,})/, 
  # 											message: "must include 1 digit."}
  # validates	:password, :format => {:with => /((?=.*[a-z]).{1,})/, 
  # 											message: "must include 1 Lower Case letter."}
  # validates :password, :format => {:with => /((?=.*[A-Z]).{1,})/, 
  # 											message: "must include 1 Upper Case letter."}
  # validates :password, :format => {:with => /(?=.*[!@#$%^&*()_+=~`]).{1,}/, 
  # 											message: "must include 1 Symbol."}

  
  # def password_complexity
  #   return if password.blank? || password =~ /((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{8,})/

  #   errors.add :password, 'Complexity requirement not met. Password Should include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  # end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def new
	end

	def create
		@category = Category.create(name: params[:categories][:name])
		redirect_to categories_path
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find_by(id: params[:id])
		@category.name = params[:category][:name]
		@category.save
		redirect_to categories_path
	end

	def show
		@category = Category.find(params[:id])
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<h1>EDIT Category</h1>

<%= form_with model: @category, local: true do |form| %>

<%= form.label :name %><br></th>
<%= form.text_field :name %>


<%= form.submit :Submit %>
<% end %>

<br>
<%= link_to 'Show all Articles', articles_path %>
<br><br>
<%= link_to 'Back to Home', root_path %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each_with_index do |category, index| %>

	<%= link_to "Category #{index+1} : #{category.name}", category_path(category) %><br><br>


<% end %>

<br>
<%= link_to "Create New Category", new_category_path %>
<br><br>
<%= link_to "Back to Categorization", categorization_path %>
<br><br>
<%= link_to 'Back to Home', root_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_with scope: :categories, url: categories_path, local: true do |form| %>

<%= form.label :name %><br></th>
<%= form.text_field :name %>


<%= form.submit :Submit %>
<% end %>

<br>
<%= link_to 'Show all categories', categories_path %>
<br><br>

<%= link_to 'Back to Home', root_path %>

</div>

app/views/categories/show.html.erb
<h1>Category View</h1>

<h3>Category: <%= label_tag 'category', @category.name %></h3>

<h3>Products</h3>
<% @category.products.each_with_index do |product, index| %>

	<%= "Product #{index+1} : #{product.name}" %><br>


<br>
<% end %>
<%= link_to 'Edit', edit_category_path(@category) %>
&emsp;
<%= link_to 'DELETE', category_path(@category), method: :delete, data: { confirm: "Are You sure to Delete \"#{@category.name}\""} %> 